// Tunable parameters.
// These will not change during runtime.
export const OPTION_CAMERA_NUDGE_ENABLED=true;
export const OPTION_HIDE_HANMARI_ON_NONINTRO_PAGES=false;
export const OPTION_NONINTRO_PAGE_HANMARI_SHRINK_FACTOR=0.8;
export const OPTION_CAMERA_NUDGE_MOUSE_SENSITIVITY=1.0;
export const OPTION_CAMERA_NUDGE_GYRO_SENSITIVITY=1.0;
export const OPTION_STAR_DENSITY_MULTIPLIER=1.0;
export const OPTION_L2D_EYE_FOLLOW_SENSITIVITY=1.0;

export const OPTION_L2D_RANDOM_ACTION_MIN_INTERVAL_SECONDS=5;
export const OPTION_L2D_RANDOM_ACTION_RAND_ADD_SECONDS=5;

export const OPTION_ENABLE_L2D_HANMARI=true;
export const OPTION_ENABLE_PARALLAX_BG=true;
export const OPTION_ENABLE_ANIMATED_STARS=true;
export const OPTION_ENABLE_FIREWORKS=true;
export const OPTION_ENABLE_L2D_FILTERS=true;

export const OPTION_TIMETABLE_REQUIRE_CLICK=true;

export const OPTION_SKY_LOGICAL_Z_LOCATION = 10000;
export const OPTION_FIREWORKS_LOGICAL_Z_LOCATION = 3000;

export const REJECT_UGLY_TRIANGLES=true;
export const UGLY_TRIANGLE_THRESHOLD_ANGLE_DEGREES = 25;

export const SCREEN_MINWIDTH_FOR_STATICBG_LR_IMAGE=1400;
