
export const tiers_data={
	standard:{
		name_en:"Standard",
		name_ko:"스탠다드",
		desc_en:"Only the essentials.",
		desc_ko:"일반 참가 등급입니다.",
		css_class:"tier-standard",
		inherits:null,
		perks_list:[
			"standard_badge",
			"standard_lanyard",
			"conbook"
		],
		inherit_exclude:[],
		price:30,
		limit:Infinity,
		icon_dark:"/sprites/tier_icons/standard_200_dark.png",
		icon_darker:"/sprites/tier_icons/standard_200_darker.png",
		icon_orig:"/sprites/tier_icons/standard_200_orig.png",
		reg_button_class:"inperson"
	},
	sponsor:{
		name_en:"Sponsor",
		name_ko:"스폰서",
		desc_en:"Includes a merch package, for those looking to support the event.",
		desc_ko:"행사를 더욱 풍성하게 후원해주실 분들을 위한 등급입니다.",
		css_class:"tier-sponsor",
		inherits:"standard",
		perks_list:[
			"conbook_website_mention",
			"shirt",
			"poster",
			"sticker_pack",
			"water_bottle",
			"hand_fan",
			"notepad",
			"tin_badge_sponsor"
		],
		inherit_exclude:[],
		price:75,
		limit:Infinity,
		icon_dark:"/sprites/tier_icons/sponsor_200_dark.png",
		icon_darker:"/sprites/tier_icons/sponsor_200_darker.png",
		icon_orig:"/sprites/tier_icons/sponsor_200_orig.png",
		reg_button_class:"inperson"
	},
	mane:{
		name_en:"Mane Six",
		name_ko:"메인식스",
		desc_en:"VIP tier, for bearers of the six Elements of Harmony.",
		desc_ko:"단 6명, 조화의 원소를 위한 특별한 VIP 등급입니다.",
		css_class:"tier-mane",
		inherits:"sponsor",
		perks_list:[
			"opening_closing_mention",
			"vendor_priority",
			"acrylic_keyring",
			"towel",
			"acrylic_stand",
			"stamp",
			"embroidered_tag",
			"tin_badge_mane"
		],
		inherit_exclude:[],
		price:150,
		limit:6,
		icon_dark:"/sprites/tier_icons/mane_200_dark.png",
		icon_darker:"/sprites/tier_icons/mane_200_darker.png",
		icon_orig:"/sprites/tier_icons/mane_200_orig.png",
		reg_button_class:"inperson",
		sold_out:true
	},
	princess:{
		name_en:"Royal Princess",
		name_ko:"로얄 프린세스",
		desc_en:"This VIP tier is dedicated to the most special three Alicorn Princesses.",
		desc_ko:"알리콘의 위엄을 담은, 최상위 3명 한정 VVIP 등급입니다.",
		css_class:"tier-princess",
		inherits:"mane",
		perks_list:[
			"backstage",
			"priority_access",
			"reserved_seating",
			"custom_badge",
			"large_tapestry",
			"relay_prompt",
			"feud_question",
			"signed_poster",
			"opening_closing_floor",
			"tin_badge_princess",
			"shipping",
			"discord_hotline",
		],
		inherit_exclude:[],
		price:400,
		limit:3,
		icon_dark:"/sprites/tier_icons/royal_200_dark.png",
		icon_darker:"/sprites/tier_icons/royal_200_darker.png",
		icon_orig:"/sprites/tier_icons/royal_200_orig.png",
		reg_button_class:"inperson",
		sold_out:true
	},
	spirit:{
		insert_divider:true,
		margin_top:48,
		name_en:"Spirit Badge",
		name_ko:"영혼참가",
		desc_en:"For those who can't make it to the event in person. You'll be able to receive the attendee badge and support the event.",
		desc_ko:"현장 방문이 어려운 분들을 위해 참가증만 배송해 드리는 후원 등급입니다.",
		css_class:"tier-spirit",
		perks_list:[
			"standard_badge",
			"standard_lanyard",
			"conbook"
		],
		inherit_exclude:[],
		price:20,
		limit:Infinity,
		icon_dark:"/sprites/tier_icons/spirit_200_dark.png",
		icon_darker:"/sprites/tier_icons/spirit_200_darker.png",
		icon_orig:"/sprites/tier_icons/spirit_200_orig.png",
		reg_button_class:"spirit"
	},
	spirit_dx:{
		name_en:"Deluxe Spirit",
		name_ko:"디럭스 영혼참가",
		desc_en:"For those who want to support the event but can't make it in person, this tier includes most of the sponsor goodies.",
		desc_ko:"현장 방문이 어려운 분들을 위해 거의 모든 특전을 배송해 드리는 후원 등급입니다.",
		css_class:"tier-spirit-dx",
		inherits:"spirit",
		perks_list:[
			"conbook_website_mention",
			"shirt",
			"poster",
			"sticker_pack",
			"water_bottle",
			"hand_fan",
			"notepad",
			"acrylic_keyring",
			"towel",
			"acrylic_stand",
			"stamp",
			"embroidered_tag",
			"signed_poster",
			"tin_badge_spirit_dx",
		],
		inherit_exclude:[],
		price:200,
		limit:Infinity,
		icon_dark:"/sprites/tier_icons/spiritplus_200_dark.png",
		icon_darker:"/sprites/tier_icons/spiritplus_200_darker.png",
		icon_orig:"/sprites/tier_icons/spiritplus_200_orig.png",
		reg_button_class:"spirit"
	},
	onsite:{
		insert_divider:true,
		margin_top:48,
		name_en:"On-Site Badge",
		name_ko:"현장등록",
		desc_en:"On-site registration during the event.<br>We recommend you pre-register as <strong>on-site registration may be limited or unavailable</strong> as venue capacity is reached.",
		desc_ko:"행사 당일 현장에서 등록할 수 있는 등급입니다.<br>인원이 한정되어 있으며, <strong>행사 안전 관리를 위해 현장등록을 진행하지 않을 수도 있으니</strong> 사전등록을 권장합니다.",
		css_class:"tier-onsite",
		inherits:null,
		perks_list:["daiso_badge","conbook"],
		inherit_exclude:[],
		price:40,
		limit:NaN,
		icon_dark:"/sprites/tier_icons/onsite_200_dark.png",
		icon_darker:"/sprites/tier_icons/onsite_200_darker.png",
		icon_orig:"/sprites/tier_icons/onsite_200_orig.png",
		reg_button_class:""
	},
};

const tin_badge_desc_ko="말랑포니의 후원자임을 증명하는 한정판 핀뱃지입니다.";
const tin_badge_desc_en="A commemorative tin badge that shows that you've supported this event.";
export const perks_data={
	standard_badge:{
		name_en:"MalangPony Badge",name_ko:"말랑포니 참가증",
		explanation_required:false,
		desc_en:"A durable plastic badge.",
		desc_ko:"PVC 재질의 목걸이형 명찰입니다."},
	custom_badge:{
		name_en:"Custom Badge",name_ko:"커스텀 참가증 제작권",
		explanation_required:true,
		desc_en:"We will create a one-of-a-kind badge, incorporating your OC or any image of your choosing into the design.",
		desc_ko:"본인의 자캐(OC)나 원하는 이미지를 넣어 세상에 단 하나뿐인 명찰을 제작해 드립니다.",
		overwrites:["standard_badge"]},
	daiso_badge:{
		name_en:"Acrylic Badge",name_ko:"일반 아크릴 명찰",
		desc_en:"For on-site registrations, an acrylic badge with a paper insert will be provided instead of a pre-registration plastic badge.",
		explanation_required:true,
		desc_ko:"현장등록자에게는 사전등록(PVC 재질) 참가증이 아닌 종이를 끼우는 아크릴 명찰이 제공됩니다."},
	standard_lanyard:{
		name_en:"Lanyard",name_ko:"랜야드",
		explanation_required:false,
		desc_en:"A lanyard with a MalangPony logo pattern.",
		explanation_required:false,
		desc_ko:"말랑포니 로고가 패턴 인쇄된 목걸이 줄입니다."},
	conbook:{
		name_en:"Conbook",name_ko:"콘북",
		explanation_required:true,
		desc_en:"The official conbook. Includes the venue information, booth information, and art.",
		desc_ko:"행사장 안내, 부스 정보, 축전 등이 담긴 공식 책자입니다."},
	conbook_website_mention:{
		name_en:"Conbook &amp; Website Mention",name_ko:"콘북 &amp; 웹페이지 기재",
		explanation_required:true,
		desc_en:"Your name will be listed on the 'Special Thanks' section of the conbook and the website credits.",
		desc_ko:"콘북 Special Thanks와 공식 웹사이트 크레딧에 닉네임을 기재해 드립니다."},
	shirt:{
		name_en:"Official T-Shirt",name_ko:"말랑포니 일러스트 티셔츠",
		explanation_required:false,
		desc_en:"A T-shirt with an event artwork.",
		desc_ko:"행사 기념 일러스트가 인쇄된 티셔츠입니다."},
	poster:{
		name_en:"A3-size Poster",name_ko:"A3 포스터",
		explanation_required:false,
		desc_en:"A print of this event's main visual.",
		desc_ko:"이번 행사의 메인 일러스트 포스터입니다."},
	sticker_pack:{
		name_en:"MalangPony Sticker Pack",name_ko:"말랑포니 스티커 팩",
		explanation_required:false,
		desc_en:"A pack of MalangPony stickers, for your luggage or laptop, etc.",
		desc_ko:"캐리어, 노트북 등에 붙이기 좋은 말랑포니 스티커 세트입니다."},
	water_bottle:{
		name_en:"MalangPony Bottle",name_ko:"말랑포니 보틀",
		explanation_required:false,
		desc_en:"A plastic water bottle with an event artwork.",
		desc_ko:"행사 기념 디자인이 새겨진 플라스틱 물병입니다."},
	hand_fan:{
		name_en:"Mascot Hand Fan",name_ko:"마스코트 부채",
		explanation_required:false,
		desc_en:"A hand fan with our mascot character, that will come in handy in hot summer days.", // pun not intended
		desc_ko:"귀여운 마스코트가 들어간 부채입니다."},
	notepad:{
		name_en:"Notepad",name_ko:"말랑포니 메모지",
		explanation_required:false,
		desc_en:"A notepad with an illustration of this event.",
		desc_ko:"말랑포니 일러스트가 들어간 떡 메모지입니다."},
	opening_closing_mention:{
		name_en:"Opening &amp; Closing Ceremonies Name Mention",name_ko:"개·폐회식 감사의 말",
		explanation_required:true,
		desc_en:"We will call out your name at the start and end of the event and express gratitude for your support.",
		desc_ko:"행사의 시작과 끝에 사회자가 직접 닉네임을 호명하며 감사의 인사를 전합니다."},
	vendor_priority:{
		name_en:"Vendor Zone Early Access",name_ko:"부스존 조기 입장",
		explanation_required:true,
		desc_en:"You'll be able to enter the Vendor Zone 30 minutes earlier, so you can browse and shop more comfortably.",
		desc_ko:"부스존에 다른 참가자보다 30분 먼저 입장하여 여유롭게 부스를 둘러보고 굿즈를 구매할 수 있습니다."},
	acrylic_keyring:{
		name_en:"Mascot Acrylic Charm",name_ko:"마스코트 아크릴 키링",
		explanation_required:false,
		desc_en:"A cute acrylic charm of our mascot that you can hang on your bags, etc.",
		desc_ko:"가방 등에 달고 다닐 수 있는 귀여운 마스코트 키링입니다."},
	towel:{
		name_en:"Commemorative Towel",name_ko:"기념 타올",
		explanation_required:true,
		desc_en:"A limited-edition towel to celebrate this event.",
		desc_ko:"말랑포니 2 개최 기념 한정판 수건입니다."},
	acrylic_stand:{
		name_en:"Acrylic Stand",name_ko:"아크릴 코롯토",
		explanation_required:false,
		desc_en:"A thick acrylic stand.",
		desc_ko:"세워둘 수 있는 두꺼운 아크릴 스탠드입니다."},
	stamp:{
		name_en:"MalangPony Stamp",name_ko:"말랑포니 기념 도장",
		explanation_required:false,
		desc_en:"A limited-edition stamp, with a special MalangPony design.",
		desc_ko:"말랑포니 디자인이 새겨진 한정판 도장입니다."},
	embroidered_tag:{
		name_en:"Embroidered Tag",name_ko:"말랑포니 자수 태그",
		explanation_required:false,
		desc_en:"A fabric tag embroidered with the cutie marks of MalangPony mascots.",
		desc_ko:"말랑포니 마스코트들의 큐티마크를 자수로 만든 키링입니다."},
	backstage:{
		name_en:"Backstage Pass",name_ko:"백스테이지 패스",
		explanation_required:true,
		desc_en:"You can enter as early as 8AM and explore the venue during setup time.",
		desc_ko:"준비 시간(오전 8시 부터) 동안 행사장 전체를 둘러볼 수 있습니다."},
	priority_access:{
		name_en:"Super Pass",name_ko:"최우선 입장",
		explanation_required:true,
		desc_en:"You may enter event halls and vendor zones earlier than any other attendee, even during set-up time.",
		desc_ko:"모든 참가자 중 가장 먼저 행사장 및 부스 구역에 입장할 수 있습니다. (준비 시간부터 체류 가능)",},
	reserved_seating:{
		name_en:"Reserved Seating",name_ko:"로얄프린세스 전용석",
		explanation_required:true,
		desc_en:"We will reserve the frontmost seats to secure the best view for you.",
		desc_ko:"메인 홀, 서브 홀의 맨 앞 좌석을 전용석으로 배정해 드립니다."},
	large_tapestry:{
		name_en:"Large Tapestry",name_ko:"대형 태피스트리",
		explanation_required:false,
		desc_en:"A large tapestry with a high-quality print of an artwork.",
		desc_ko:"고화질 일러스트가 인쇄된 족자봉입니다."},
	relay_prompt:{
		name_en:"Relay Sketches Prompt",name_ko:"릴레이 스케치 주제 선택권",
		explanation_required:true,
		desc_en:"You can choose which scene from the show that will get drawn in the Relay Pony Sketches panel.",
		desc_ko:"릴레이 포니 스케치 패널에서 다함께 그릴 포니 장면을 선택하실 수 있습니다."},
	feud_question:{
		name_en:"Choose Brony Feud Question",name_ko:"브로니 말 맞추기 질문 선택권",
		explanation_required:true,
		desc_en:"You can choose a question that will be in the survey for the Brony Feud panel.",
		desc_ko:"브로니 말 맞추기 패널의 설문조사에 들어갈 질문을 하나 지정하실 수 있습니다."},
	signed_poster:{
		name_en:"Poster Signed by Staff",name_ko:"스태프 사인 포스터",
		explanation_required:false,
		desc_en:"A poster signed by all the staff and guests, expressing our gratitude for your support.",
		desc_ko:"행사를 만들어간 모든 스태프와 게스트의 존경과 감사가 담긴 포스터입니다."},
	opening_closing_floor:{
		name_en:"Oppertunity to Speak at Opening/Closing",name_ko:"개·폐회식 축사",
		explanation_required:true,
		desc_en:"You'll be able to come up on stage and freely talk for a short period of time. (Optional)",
		desc_ko:"원하실 경우, 개·폐회식 때 무대에 올라와 참가자들에게 짧은 인사나 소감을 발표할 수 있는 시간을 드립니다."},
	shipping:{
		name_en:"Shipping Service",name_ko:"배송 서비스",
		explanation_required:true,
		desc_en:"We will ship all the heavy merchandise you have purchased or received during the event, free of charge. (Optional)",
		desc_ko:"원하실 경우, 현장에서 수령한 무거운 굿즈들을 택배로 발송해 드립니다."},
	discord_hotline:{
		name_en:"Discord Hotline",name_ko:"디스코드 핫라인",
		explanation_required:true,
		desc_en:"You'll be invited to a dedicated Discord channel in which you can directly chat with the event staff. Any suggestions you tell us through this channel will be given utmost priotity.",
		desc_ko:"운영진과 직접 소통할 수 있는 전용 디스코드 채널에 초대되며, 건의사항을 말씀해 주신다면 최우선으로 검토합니다."},
	tin_badge_sponsor:{
		name_en:"Sponsor Tin Badge",name_ko:"스폰서 전용 핀뱃지",
		explanation_required:false,
		desc_en:tin_badge_desc_en,
		desc_ko:tin_badge_desc_ko},
	tin_badge_mane:{
		name_en:"Mane Six Tin Badge",name_ko:"메인식스 전용 핀뱃지",
		explanation_required:false,
		desc_en:tin_badge_desc_en,
		desc_ko:tin_badge_desc_ko,
		overwrites:["tin_badge_sponsor"]},
	tin_badge_princess:{
		name_en:"Royal Princess Tin Badge",name_ko:"로얄프린세스 전용 핀뱃지",
		explanation_required:false,
		desc_en:tin_badge_desc_en,
		desc_ko:tin_badge_desc_ko,
		overwrites:["tin_badge_mane","tin_badge_sponsor"]},
	tin_badge_spirit_dx:{
		name_en:"Deluxe Spirit Tin Badge",name_ko:"디럭스 영혼참가 전용 핀뱃지",
		explanation_required:false,
		desc_en:tin_badge_desc_en,
		desc_ko:tin_badge_desc_ko},
};
